package org.kiki_cpg_v2.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PaymentTransactions generated by hbm2java
 */
@Entity
@Table(name = "payment_transactions")
public class PaymentTransactionsEntity {

	@Id
	@Column(name = "TID")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@Column(name = "SubscriptionPaymentID")
	private Integer subscriptionPaymentId;

	@Column(name = "PaymentMethodID")
	private Integer paymentMethodId;

	@Column(name = "TransactionID")
	private String transactionId;

	@Column(name = "CreatedDate")
	private Date createdDate;

	@Column(name = "LastUpdatedDate")
	private Date lastUpdatedDate;

	@Column(name = "Status")
	private Integer status;

	@Column(name = "IPGResponse")
	private String ipgresponse;

	@Column(name = "IPGError")
	private String ipgerror;

	@Column(name = "Token")
	private String token;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSubscriptionPaymentId() {
		return subscriptionPaymentId;
	}

	public void setSubscriptionPaymentId(Integer subscriptionPaymentId) {
		this.subscriptionPaymentId = subscriptionPaymentId;
	}

	public Integer getPaymentMethodId() {
		return paymentMethodId;
	}

	public void setPaymentMethodId(Integer paymentMethodId) {
		this.paymentMethodId = paymentMethodId;
	}

	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastUpdatedDate() {
		return lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getIpgresponse() {
		return ipgresponse;
	}

	public void setIpgresponse(String ipgresponse) {
		this.ipgresponse = ipgresponse;
	}

	public String getIpgerror() {
		return ipgerror;
	}

	public void setIpgerror(String ipgerror) {
		this.ipgerror = ipgerror;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
