package org.kiki_cpg_v2.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ViewerCodes generated by hbm2java
 */
@Entity
@Table(name = "viewer_codes")
public class ViewerCodesEntity{

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "rec_id")
	private Integer id;

	@Column(name = "viewer_id")
	private Integer viewerId;

	@Column(name = "scratch_card_id")
	private Integer scratchCardId;

	@Column(name = "action_time")
	private Date actionTime;

	@Column(name = "status")
	private Integer status;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getViewerId() {
		return viewerId;
	}

	public void setViewerId(Integer viewerId) {
		this.viewerId = viewerId;
	}

	public Integer getScratchCardId() {
		return scratchCardId;
	}

	public void setScratchCardId(Integer scratchCardId) {
		this.scratchCardId = scratchCardId;
	}

	public Date getActionTime() {
		return actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
